Remove unused private fields
During the development of a forthcoming commit that replaces private
unimplemented special member functions with explicitly deleted ones, we
got a surprising improvement of compiler diagnostics: Clang started to
see a lot of unused private fields that are masked by the fact that
there were unimplemented functions in the class. This makes sense
because the ostensibly unused field _could be_ used by a method whose
definition compiler hasn't seen in the current translation unit -- it
also suggests that the compiler would be better equipped at detecting
this if we had used whole-program analysis.

A sample of the errors looks like the following:

In file included from CMiniDumper.cpp:14:
In file included from ../../../../../../src/backend/gporca/libgpos/include/gpos/error/CErrorContext.h:17:
../../../../../../src/backend/gporca/libgpos/include/gpos/error/CMiniDumper.h:32:15: error: private field 'm_mp' is not used [-Werror,-Wunused-private-field]
        CMemoryPool *m_mp;
                     ^
1 error generated.

There are 12 such warnings, and this commit fixes them all. Note that
code mortality is a chain reaction: oftentimes, a variable (including
parameter) is only live because it's passed to another variable. While I
was at it, I also performed chained removal of variables and parameters
that became dead after removing the dead fields.